matches:
    # Shorthands
  - trigger: ":nn:"
    replace: "NOT NULL"
  - trigger: ":pk:"
    replace: "PRIMARY KEY"
  - trigger: ":fk:"
    replace: "FOREING KEY ($|$) REFERENCES tbl(col)"
  - trigger: ":ie:"
    replace: "IF EXISTS "
  - trigger: ":ife:"
    replace: "IF NOT EXISTS "
  - trigger: ":btw:"
    replace: BETWEEN $|$ AND
  - trigger: ":l:"
    replace: "LIKE '$|$'"
  - trigger: ":nl:"
    replace: "NOT LIKE '$|$'"
  - trigger: ":in:"
    replace: "IN ($|$)"

    # DQL
  - trigger: ":g:"
    replace: "GROUP BY $|$"
  - trigger: ":h:"
    replace: "HAVING $|$"
  - trigger: ":or:"
    replace: "ORDER BY $|$"
  - trigger: ":ord:"
    replace: "ORDER BY $|$ DESC"
  - trigger: ":sf:"
    replace: "SELECT\n\t$|$\nFROM"
  - trigger: ":w:"
    replace: "WHERE $|$"
  - trigger: ":we:"
    replace: "WHERE EXISTS (\n\t$|$\n)"
  - trigger: ":a:"
    replace: "\n\tAND ($|$)"
  - trigger: ":o:"
    replace: "\n\tOR ($|$)"
  - trigger: ":wi:"
    replace: "WITH $|$ AS (\n\t\n)"
  - trigger: ":as:"
    replace: ",\n$|$ AS (\n\t\n)"

    # Joins
  - trigger: ":ij:"
    replace: "INNER JOIN $|$ AS\n\tON "
  - trigger: ":lj:"
    replace: "LEFT JOIN $|$ AS\n\tON "
  - trigger: ":rj:"
    replace: "RIGHT JOIN $|$ AS\n\tON "
  - trigger: ":fj:"
    replace: "FULL JOIN $|$ AS\n\tON "
  - trigger: ":u:"
    replace: "\n\tUNION\n"
  - trigger: ":ua:"
    replace: "\n\tUNION ALL\n"

    # DDL
  - trigger: ":cd:"
    replace: "CREATE DATABASE $|$;"
  - trigger: ":ci:"
    replace: "CREATE INDEX $|$\n\tON"
  - trigger: ":ct:"
    REPLACE: "CREATE TABLE $|$ (\n\n);"
  - trigger: ":cta:"
    REPLACE: "CREATE TABLE $|$ AS\n"
  - trigger: ":cva:"
    replace: "CREATE VIEW $|$ AS\n"
  - trigger: ":ad:"
    replace: "ALTER DATABASE $|$"
  - trigger: ":at:"
    replace: "ALTER TABLE $|$"
  - trigger: ":av:"
    replace: "ALTER VIEW $|$"
  - trigger: ":dd:"
    replace: "DROP DATABASE $|$;"
  - trigger: ":di:"
    replace: "DROP INDEX $|$;"
  - trigger: ":dt:"
    replace: "DROP TABLE $|$;"
  - trigger: ":co:"
    replace: "COMMENT '$|$' ON"
  - trigger: ":re:"
    replace: "RENAME $|$ TO"
  - trigger: ":tr:"
    replace: "TRUNCATE TABLE $|$;"

    # DCL
  - trigger: ":go:"
    replace: "GRANT OPTION"
  - trigger: ":got:"
    replace: "GRANT $|$\n\tON\n\tTO"
  - trigger: ":rot:"
    replace: "REVOKE $|$\n\tON\n\tTO"
  - trigger: ":cs:"
    replace: "CASCADE;"

    # DML
  - trigger: ":iis:"
    replace: "INSERT INTO $|$ ( )\n\tVALUES ( )"
  - trigger: ":up:"
    replace: "UPDATE $|$\nSET"
  - trigger: ":del:"
    replace: "DELETE FROM"
  - trigger: ":ex:"
    replace: "EXPLAIN PLAN FOR\n"
  - trigger: ":lc:"
    replace: "LOCK $|$ IN"
  - trigger: ":ca:"
    replace: "CALL $|$();"

    # TCL

    # PGL
  - trigger: ":ex:"
    replace: "EXPLAIN PLAN FOR\n"

