matches:
    # Shorthands
  - trigger: ":nn:"
    replace: "NOT NULL"
  - trigger: ":ie:"
    replace: "IF EXISTS "
  - trigger: ":ife:"
    replace: "IF NOT EXISTS "
  - trigger: ":btw:"
    replace: "BETWEEN $|$ AND"
  - trigger: ":l:"
    replace: "LIKE '$|$'"
  - trigger: ":nl:"
    replace: "NOT LIKE '$|$'"
  - trigger: ":in:"
    replace: "IN ($|$)"

    # Aggregates
  - trigger: ":count:"
    replace: "COUNT($|$) AS"
  - trigger: ":sum:"
    replace: "SUM($|$) AS"
  - trigger: ":avg:"
    replace: "AVG($|$) AS"
  - trigger: ":max:"
    replace: "MAX($|$) AS"
  - trigger: ":min:"
    replace: "MIN($|$) AS"
  - trigger: ":rank:"
    replace: "RANK($|$) AS"
  - trigger: ":over:"
    replace: "OVER($|$)"
  - trigger: ":pb:"
    replace: "PARTITION BY "
  - trigger: ":first:"
    replace: "FIRST_VALUE() AS"
  - trigger: ":last:"
    replace: "LAST_VALUE() AS"
  - trigger: ":lag:"
    replace: "LAG() AS"
  - trigger: ":lead:"
    replace: "LEAD() AS"
  - trigger: ":row:"
    replace: "ROW_NUMBER() AS"


    # DQL
  - trigger: ":gb:"
    replace: "GROUP BY $|$"
  - trigger: ":h:"
    replace: "HAVING $|$"
  - trigger: ":ob:"
    replace: "ORDER BY $|$"
  - trigger: ":obd:"
    replace: "ORDER BY $|$ DESC"
  - trigger: ":sf:"
    replace: "SELECT\n\t$|$\nFROM"
  - trigger: ":w:"
    replace: "WHERE $|$"
  - trigger: ":we:"
    replace: "WHERE EXISTS (\n\t$|$\n)"
  - trigger: ":and:"
    replace: "\n\tAND ($|$)"
  - trigger: ":or:"
    replace: "\n\tOR ($|$)"
  - trigger: ":wi:"
    replace: "WITH $|$ AS (\n\t\n)"
  - trigger: ":as:"
    replace: ",\n$|$ AS (\n\t\n)"

    # Joins
  - trigger: ":ij:"
    replace: "INNER JOIN $|$ AS\n\tON "
  - trigger: ":lj:"
    replace: "LEFT JOIN $|$ AS\n\tON "
  - trigger: ":rj:"
    replace: "RIGHT JOIN $|$ AS\n\tON "
  - trigger: ":fj:"
    replace: "FULL JOIN $|$ AS\n\tON "
  - trigger: ":u:"
    replace: "\n\tUNION\n"
  - trigger: ":ua:"
    replace: "\n\tUNION ALL\n"

    # DDL
  - trigger: ":cd:"
    replace: "CREATE DATABASE $|$;"
  - trigger: ":ci:"
    replace: "CREATE INDEX $|$\n\tON"
  - trigger: ":ct:"
    REPLACE: "CREATE TABLE $|$ (\n\n);"
  - trigger: ":cta:"
    REPLACE: "CREATE TABLE $|$ AS\n"
  - trigger: ":cva:"
    replace: "CREATE VIEW $|$ AS\n"
  - trigger: ":ad:"
    replace: "ALTER DATABASE $|$"
  - trigger: ":at:"
    replace: "ALTER TABLE $|$"
  - trigger: ":av:"
    replace: "ALTER VIEW $|$"
  - trigger: ":dd:"
    replace: "DROP DATABASE $|$;"
  - trigger: ":di:"
    replace: "DROP INDEX $|$;"
  - trigger: ":dt:"
    replace: "DROP TABLE $|$;"
  - trigger: ":co:"
    replace: "COMMENT '$|$' ON"
  - trigger: ":re:"
    replace: "RENAME $|$ TO"
  - trigger: ":tr:"
    replace: "TRUNCATE TABLE $|$;"

    # Constraints
  - trigger: ":un:"
    replace: "UNIQUE ($|$)"
  - trigger: ":nd:"
    replace: "NULLS DISTINCT"
  - trigger: ":nnd:"
    replace: "NULLS NOT DISTINCT"
  - trigger: ":pk:"
    replace: "PRIMARY KEY"
  - trigger: ":fk:"
    replace: "FOREING KEY ($|$) REFERENCES"

    # DCL
  - trigger: ":go:"
    replace: "GRANT OPTION"
  - trigger: ":got:"
    replace: "GRANT $|$\n\tON\n\tTO"
  - trigger: ":rot:"
    replace: "REVOKE $|$\n\tON\n\tTO"
  - trigger: ":cs:"
    replace: "CASCADE;"

    # DML
  - trigger: ":iis:"
    replace: "INSERT INTO $|$ ( )\n\tVALUES ( )"
  - trigger: ":up:"
    replace: "UPDATE $|$\nSET"
  - trigger: ":df:"
    replace: "DELETE FROM"
  - trigger: ":ex:"
    replace: "EXPLAIN PLAN FOR\n"
  - trigger: ":lc:"
    replace: "LOCK $|$ IN"
  - trigger: ":cpa:"
    replace: "CREATE PROCEDURE '$|$' AS\nBEGIN\n\nEND;"
  - trigger: ":cp:"
    replace: "CALL $|$();"

    # TCL
  - trigger: ":bt:"
    replace: "BEGIN TRANSACTION $|$;"
  - trigger: ":c:"
    replace: "COMMIT;"
  - trigger: ":r:"
    replace: "ROLLBACK;"
  - trigger: ":s:"
    replace: "SAVEPOINT $|$"

    # PGL
  - trigger: ":cpg:"
    replace: "CREATE PROPERTY GRAPH $|$\n\tVERTEX TABLES ()\n\tEDGE TABLES();"
  - trigger: ":gt:"
    replace: "GRAPH_TABLE (\n\n)"
  - trigger: ":m:"
    replace: "\n\tMATCH ($|$)"
  - trigger: ":>:"
    replace: "\n\t\t-[:$|$]-> (:)"
  - trigger: ":<:"
    replace: "\n\t\t<-[:$|$]- (:)"
  - trigger: ":cols:"
    replace: "\n\t COLUMNS ()"

