matches:
  # Shorthands
  - trigger: ";d;"
    replace: "DISTINCT $|$"
  - trigger: ";n;"
    replace: "NULL"
  - trigger: ";nn;"
    replace: "NOT NULL"
  - trigger: ";ie;"
    replace: "IF EXISTS"
  - trigger: ";ife;"
    replace: "IF NOT EXISTS"
  - trigger: ";btw;"
    replace: "BETWEEN $|$ AND"
  - trigger: ";btws;"
    replace: "BETWEEN SYMMETRIC $|$ AND"
  - trigger: ";l;"
    replace: "LIKE '$|$'"
  - trigger: ";nl;"
    replace: "NOT LIKE '$|$'"
  - trigger: ";st;"
    replace: "SIMILAR TO '$|$'"
  - trigger: ";nst;"
    replace: "NOT SIMILAR TO '$|$'"
  - trigger: ";in;"
    replace: "IN ($|$)"
  - trigger: ";ex;"
    replace: "EXISTS (\n\t$|$\n)"
  - trigger: ";some;"
    replace: "SOME (\n\t$|$\n)"
  - trigger: ";and;"
    replace: "\n\tAND ($|$)"
  - trigger: ";or;"
    replace: "\n\tOR ($|$)"

    # functions
  - trigger: ";coal;"
    replace: "COALESCE($|$, )"
  - trigger: ";corr;"
    replace: "CORR($|$, )"
  - trigger: ";cast;"
    replace: "CAST($|$ AS )"
  - trigger: ";round;"
    replace: "ROUND($|$, 2)"
  - trigger: ";sub;"
    replace: "SUBSTRING($|$ FROM FOR )"
  - trigger: ";substr;"
    replace: "SUBSTRING($|$, , )"
  - trigger: ";low;"
    replace: "LOWER($|$)"
  - trigger: ";upp;"
    replace: "UPPER($|$)"
  - trigger: ";incap;"
    replace: "INITCAP($|$)"
  - trigger: ";len;"
    replace: "LENGTH($|$)"
  - trigger: ";clen;"
    replace: "CHAR_LENGTH($|$)"
  - trigger: ";pos;"
    replace: "POSITION('$|$' IN )"
  - trigger: ";spos;"
    replace: "STRPOS($|$, '')"
  - trigger: ";left;"
    replace: "LEFT($|$, )"
  - trigger: ";right;"
    replace: "RIGHT($|$, )"
  - trigger: ";rep;"
    replace: "REPLACE($|$, , )"
  - trigger: ";rev;"
    replace: "REVERSE($|$)"
  - trigger: ";trim;"
    replace: "TRIM()"
  - trigger: ";rtrim;"
    replace: "RTRIM($|$, )"
  - trigger: ";ltrim;"
    replace: "LTRIM($|$, )"
  - trigger: ";lpad;"
    replace: "LPAD($|$, )"
  - trigger: ";rpad;"
    replace: "RPAD($|$, )"
  - trigger: ";sa;"
    replace: "STRING_AGG($|$, )"
  - trigger: ";any;"
    replace: "ANY ($|$)"
  - trigger: ";contains;"
    replace: "@> ARRAY['$|$']"
    # Datetime
  - trigger: ";extr;"
    replace: "EXTRACT($|$ FROM )"
  - trigger: ";inter;"
    replace: "INTERVAL '$|$'"
  - trigger: ";date;"
    replace: "DATE '$|$'"
  - trigger: ";ts;"
    replace: "TIMESTAMP '$|$'"
  - trigger: ";tsz;"
    replace: "TIMESTAMPTZ '$|$'"
  - trigger: ";time;"
    replace: "TIME '$|$'"
  - trigger: ";ol;"
    replace: "OVERLAPS ('$|$', )"
  - trigger: ";age;"
    replace: "AGE($|$)"

    # conditionals
  - trigger: ";case;"
    replace: "CASE $|$\nEND"
  - trigger: ";caseas;"
    replace: "CASE $|$\nEND AS"
  - trigger: ";when;"
    replace: "WHEN $|$ THEN"

    # DQL
  - trigger: ";with;"
    replace: "WITH $|$ AS (\n\t\n)"
  - trigger: ";as;"
    replace: ",\n$|$ AS (\n\t\n)"
  - trigger: ";s;"
    replace: "SELECT $|$"
  - trigger: ";f;"
    replace: "FROM $|$"
  - trigger: ";sf;"
    replace: "SELECT\n\nFROM $|$ AS"
  - trigger: ";w;"
    replace: "WHERE $|$"
  - trigger: ";h;"
    replace: "HAVING $|$"
  - trigger: ";ob;"
    replace: "ORDER BY $|$"
  - trigger: ";obd;"
    replace: "ORDER BY $|$ DESC"
  - trigger: ";oba;"
    replace: "ORDER BY $|$ ASC"

    # Sampling
  - trigger: ";sample;"
    replace: "TABLESAMPLE SYSTEM ($|$)"
  - trigger: ";rsample;"
    replace: "TABLESAMPLE SYSTEM ($|$) REPEATABLE()"
  - trigger: ";berm;"
    replace: "TABLESAMPLE BERMOULLI ($|$)"
  - trigger: ";rberm;"
    replace: "TABLESAMPLE BERMOULLI ($|$) REPEATABLE()"

    # Aggregates
  - trigger: ";gb;"
    replace: "GROUP BY $|$"
  - trigger: ";cube;"
    replace: "CUBE($|$, )"
  - trigger: ";roll;"
    replace: "ROLLUP($|$)"
  - trigger: ";gs;"
    replace: "GROUPING SETS(\n$|$\n)"
  - trigger: ";count;"
    replace: "COUNT($|$)"
  - trigger: ";countas;"
    replace: "COUNT($|$) AS"
  - trigger: ";sum;"
    replace: "SUM($|$)"
  - trigger: ";sumas;"
    replace: "SUM($|$) AS"
  - trigger: ";avg;"
    replace: "AVG($|$)"
  - trigger: ";avgas;"
    replace: "AVG($|$) AS"
  - trigger: ";max;"
    replace: "MAX($|$)"
  - trigger: ";maxas;"
    replace: "MAX($|$) AS"
  - trigger: ";min;"
    replace: "MIN($|$)"
  - trigger: ";minas;"
    replace: "MIN($|$) AS"
  - trigger: ";std;"
    replace: "STDDEV($|$)"
  - trigger: ";stdas;"
    replace: "STDDEV($|$) AS"

    # Window functions
  - trigger: ";win;"
    replace: "WINDOW $|$ AS ()"
  - trigger: ";over;"
    replace: "OVER($|$)"
  - trigger: ";pb;"
    replace: "PARTITION BY "
  - trigger: ";rnum;"
    replace: "ROW_NUMBER() OVER($|$) AS"
  - trigger: ";rank;"
    replace: "RANK() OVER($|$) AS"
  - trigger: ";drank;"
    replace: "DENSE_RANK() OVER($|$) AS"
  - trigger: ";first;"
    replace: "FIRST_VALUE($|$) OVER() AS"
  - trigger: ";last;"
    replace: "LAST_VALUE($|$) OVER() AS"
  - trigger: ";lag;"
    replace: "LAG($|$) OVER() AS"
  - trigger: ";lead;"
    replace: "LEAD($|$) OVER() AS"
  - trigger: ";ntile;"
    replace: "NTILE($|$) OVER() AS"
    # window frames
  - trigger: ";rowb;"
    replace: "ROWS BETWEEN $|$ AND"
  - trigger: ";ranb;"
    replace: "range BETWEEN $|$ AND"
  - trigger: ";prec;"
    replace: "$|$ PRECEDING"
  - trigger: ";unprec;"
    replace: "UNBOUNDED PRECEDING"
  - trigger: ";foll;"
    replace: "$|$ FOLLOWING"
  - trigger: ";unfoll;"
    replace: "UNBOUNDED FOLLOWING"
  - trigger: ";cr;"
    replace: "CURRENT ROW"

    # Joins
  - trigger: ";ij;"
    replace: "INNER JOIN $|$ AS\n\tON "
  - trigger: ";lj;"
    replace: "LEFT JOIN $|$ AS\n\tON "
  - trigger: ";rj;"
    replace: "RIGHT JOIN $|$ AS\n\tON "
  - trigger: ";fj;"
    replace: "FULL OUTER JOIN $|$ AS\n\tON "
  - trigger: ";cj;"
    replace: "CROSS JOIN $|$ AS"
  - trigger: ";nj;"
    replace: "NATURAL JOIN $|$ AS"
  - trigger: ";nlj;"
    replace: "NATURAL LEFT JOIN $|$ AS"
  - trigger: ";nrj;"
    replace: "NATURAL RIGHT JOIN $|$ AS"
  - trigger: ";u;"
    replace: "\n\tUNION\n"
  - trigger: ";ua;"
    replace: "\n\tUNION ALL\n"
  - trigger: ";exc;"
    replace: "\n\tEXCEPT\n"
  - trigger: ";int;"
    replace: "\n\tINTERSECT\n"
  - trigger: ";lat;"
    replace: "LATERAL $|$"
  - trigger: ";us;"
    replace: "USING $|$"
  - trigger: ";off;"
    replace: "OFFSET $|$"
  - trigger: ";fet;"
    replace: "FETCH $|$ ROW ONLY;"

    # DDL
  - trigger: ";cd;"
    replace: "CREATE DATABASE $|$;"
  - trigger: ";ci;"
    replace: "CREATE INDEX $|$\n\tON"
  - trigger: ";ct;"
    replace: "CREATE TABLE $|$ (\n\n);"
  - trigger: ";ctt;"
    replace: "CREATE TEMP TABLE $|$ (\n\n);"
  - trigger: ";ctas;"
    replace: "CREATE TABLE $|$ AS\n"
  - trigger: ";cv;"
    replace: "CREATE VIEW $|$ AS\n"
  - trigger: ";ctv;"
    replace: "CREATE TEMP VIEW $|$ AS\n"
  - trigger: ";ad;"
    replace: "ALTER DATABASE $|$"
  - trigger: ";at;"
    replace: "ALTER TABLE $|$"
  - trigger: ";av;"
    replace: "ALTER VIEW $|$"
  - trigger: ";dd;"
    replace: "DROP DATABASE $|$;"
  - trigger: ";di;"
    replace: "DROP INDEX $|$;"
  - trigger: ";dt;"
    replace: "DROP TABLE $|$;"
  - trigger: ";co;"
    replace: "COMMENT '$|$' ON"
  - trigger: ";re;"
    replace: "RENAME $|$ TO"
  - trigger: ";tr;"
    replace: "TRUNCATE TABLE $|$;"

    # Constraints
  - trigger: ";cons;"
    replace: "CONSTRAINT $|$"
  - trigger: ";un;"
    replace: "UNIQUE ($|$)"
  - trigger: ";nd;"
    replace: "NULLS DISTINCT"
  - trigger: ";nnd;"
    replace: "NULLS NOT DISTINCT"
  - trigger: ";pk;"
    replace: "PRIMARY KEY"
  - trigger: ";fk;"
    replace: "FOREING KEY ($|$) REFERENCES"
  - trigger: ";ch;"
    replace: "CHECK ($|$)"
  - trigger: ";ga;"
    replace: "GENERATED ALWAYS AS ($|$)"
  - trigger: ";gas;"
    replace: "GENERATED ALWAYS AS ($|$) STORED"
  - trigger: ";inh;"
    replace: "INHERITS ($|$)"
  - trigger: ";wo;"
    replace: "WITHOUT OVERLAPS"

    # DCL
  - trigger: ";go;"
    replace: "GRANT OPTION"
  - trigger: ";got;"
    replace: "GRANT $|$\n\tON\n\tTO"
  - trigger: ";rot;"
    replace: "REVOKE $|$\n\tON\n\tTO"
  - trigger: ";cs;"
    replace: "CASCADE;"

    # DML
  - trigger: ";iis;"
    replace: "INSERT INTO $|$ ( )\n\tVALUES ( )"
  - trigger: ";up;"
    replace: "UPDATE $|$\nSET"
  - trigger: ";df;"
    replace: "DELETE FROM"
  - trigger: ";expl;"
    replace: "EXPLAIN PLAN FOR\n"
  - trigger: ";lc;"
    replace: "LOCK $|$ IN"
  - trigger: ";cpa;"
    replace: "CREATE PROCEDURE '$|$' AS\nBEGIN\n\nEND;"
  - trigger: ";cp;"
    replace: "CALL $|$();"

    # TCL
  - trigger: ";bt;"
    replace: "BEGIN TRANSACTION $|$;"
  - trigger: ";c;"
    replace: "COMMIT;"
  - trigger: ";rb;"
    replace: "ROLLBACK;"
  - trigger: ";save;"
    replace: "SAVEPOINT $|$"

    # PGL
  - trigger: ";cpg;"
    replace: "CREATE PROPERTY GRAPH $|$\n\tVERTEX TABLES ()\n\tEDGE TABLES();"
  - trigger: ";gt;"
    replace: "GRAPH_TABLE (\n\n)"
  - trigger: ";m;"
    replace: "\n\tMATCH ($|$)"
  - trigger: ";>;"
    replace: "\n\t\t-[:$|$]-> (:)"
  - trigger: ";<;"
    replace: "\n\t\t<-[:$|$]- (:)"
  - trigger: ";cols;"
    replace: "\n\t COLUMNS ()"
